// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpcyxgkxqkknrdycfpxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwY3l4Z2t4cWtrbnJkeWNmcHhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDcxMTAsImV4cCI6MjA1ODk4MzExMH0.kX3U0QaTrFMoWka_ulliP4TNb--PynLD4XrVO1s4_Ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);